name: ShotIQ
options:
  bundleIdPrefix: com.enes.shotiq
configs:
  Debug: debug
  Release: release
packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift
    from: 2.0.0
targets:
  ShotIQ:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ShotIQ
        includes:
          - "**/*.swift"
        excludes:
          - "Assets.xcassets/**"
      - path: ShotIQ/Assets.xcassets
        type: folder
        buildPhase: resources
    info:
      path: ShotIQ/Info.plist
      properties:
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        EDGE_ANALYZE_URL: $(EDGE_ANALYZE_URL)
        NSCameraUsageDescription: ShotIQ uses your camera to record practice shots for AI analysis.
        NSMicrophoneUsageDescription: ShotIQ uses your microphone to capture audio during shot recording.
    settings:
      base:
        INFOPLIST_FILE: ShotIQ/Info.plist
        OTHER_SWIFT_FLAGS: "-DDEBUG"
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.enes.shotiq.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    configFiles:
      Debug: Config.xcconfig
      Release: Config.xcconfig
    dependencies:
      - package: Supabase
        product: Supabase
    scheme:
      testTargets: []
