name: CourtVision
options:
  bundleIdPrefix: com.enes.courtvision
configs:
  Debug: debug
  Release: release
packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift
    from: 2.0.0
targets:
  CourtVision:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CourtVision
        includes:
          - "**/*.swift"
        excludes:
          - "Assets.xcassets/**"
      - path: CourtVision/Assets.xcassets
        type: folder.assetcatalog
    info:
      path: CourtVision/Info.plist
      properties:
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        EDGE_ANALYZE_URL: $(EDGE_ANALYZE_URL)
        NSCameraUsageDescription: CourtVision uses your camera to record practice shots for AI analysis.
        NSMicrophoneUsageDescription: CourtVision uses your microphone to capture audio during shot recording.
        NSPhotoLibraryUsageDescription: CourtVision needs access to your photo library to upload basketball shot videos for AI analysis and coaching tips.
    settings:
      base:
        INFOPLIST_FILE: CourtVision/Info.plist
        OTHER_SWIFT_FLAGS: "-DDEBUG"
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.enes.courtvision.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    configFiles:
      Debug: Config.xcconfig
      Release: Config.xcconfig
    dependencies:
      - package: Supabase
        product: Supabase
    scheme:
      testTargets: []
